"""Whole chr22 gene-level simulation from PLINK genotype data.

This script extends the small-window simulation in ``simulation.py`` to a full
chromosome by using SNP-to-gene annotation to process one gene block at a time.
It can use one PLINK prefix and split samples into pop1/pop2/tissue sets, or two
PLINK prefixes when population-specific genotypes are available.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import itertools
import math
import sys
import time
from collections import defaultdict
from collections.abc import Sequence
from pathlib import Path

import numpy as np
import pandas as pd

ROOT_DIR = Path(__file__).resolve().parents[4]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from traceCB.gmm import GMM, GMMtissue  # noqa: E402
from traceCB.ldsc import Run_Cross_LDSC  # noqa: E402
from traceCB.utils import MAX_CORR, MIN_FLOAT, MIN_HERITABILITY, z2p  # noqa: E402

P_VALUE_THRESHOLD = 0.05
DEFAULT_OMEGA_P_THRESHOLD = 0.10
BED_MISSING = np.nan
ARCHITECTURES = ("shared", "pop1_specific", "pop2_specific", "null")
DEFAULT_ARCHITECTURE_PROBS = [0.25, 0.25, 0.25, 0.25]
GRID_PARAMETER_NAMES = (
    "h1sq",
    "h2sq",
    "gc",
    "n1",
    "n2",
    "nt",
    "propt",
    "pcausal",
)
SINGLE_GRID_DEFAULTS = {
    "h1sq": [0.1],
    "h2sq": [0.1],
    "gc": [0.7],
    "n1": [100],
    "n2": [400],
    "nt": [1000],
    "propt": [0.2],
    "pcausal": [0.005],
}
MIXTURE_GRID_DEFAULTS = {
    "h1sq": [0.1],
    "h2sq": [0.1, 0.2],
    "gc": [0.7],
    "n1": [100],
    "n2": [100, 400],
    "nt": [5000],
    "propt": [0.01, 0.3, 0.6],
    "pcausal": [0.005],
}
MIXTURE_INPUT_DEFAULTS = {
    "pop1_plink_prefix": "data/simulation/wg_ukb/height_merge_qc2_chr22",
    "pop2_plink_prefix": "data/simulation/ukb/height_ukb_50k_chr22",
    "pop2_flip_snps": "data/simulation/chr22_eqtl/chr22.pop2_flip_to_pop1.txt",
    "ld_pop1": "data/simulation/chr22_eqtl/ld_harmonized/TAR_AUX_std_chr22_pop1.gz",
    "ld_pop2": "data/simulation/chr22_eqtl/ld_harmonized/TAR_AUX_std_chr22_pop2.gz",
    "ld_cross": "data/simulation/chr22_eqtl/ld_harmonized/TAR_AUX_std_chr22_te.gz",
}


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run whole chr22 traceCB simulation using PLINK genotypes."
    )
    parser.add_argument(
        "--run_prefix",
        default=None,
        help="Run a mixture parameter grid and use this prefix for generated run names.",
    )
    parser.add_argument(
        "--plink_prefix",
        default="/Users/lucajiang/learn/CityU/UKBheight/height_ukb_50k_chr22",
        help="PLINK prefix used for all samples. Samples are split into pop1/pop2/tissue.",
    )
    parser.add_argument(
        "--pop1_plink_prefix",
        default=None,
        help="Optional PLINK prefix for population 1. Overrides --plink_prefix for pop1.",
    )
    parser.add_argument(
        "--pop2_plink_prefix",
        default=None,
        help="Optional PLINK prefix for population 2 and tissue. Overrides --plink_prefix for pop2/tissue.",
    )
    parser.add_argument(
        "--snp_gene",
        default="data/simulation/chr22_eqtl/chr22.snp_gene_500kb.tsv",
        help="SNP-gene long annotation generated by prepare_chr22_eqtl_inputs.py.",
    )
    parser.add_argument("--ld_pop1", default=None, help="s-ldxr pop1 LD score .gz.")
    parser.add_argument("--ld_pop2", default=None, help="s-ldxr pop2 LD score .gz.")
    parser.add_argument(
        "--ld_cross", default=None, help="s-ldxr trans-ethnic LD score .gz."
    )
    parser.add_argument(
        "--pop2_flip_snps",
        default=None,
        help="Optional SNP list whose pop2 dosage should be flipped to pop1 allele order.",
    )
    parser.add_argument(
        "--use_sample_ld",
        action="store_true",
        help="Calculate LD from simulated samples instead of s-ldxr LD score files.",
    )
    parser.add_argument("--runname", default="chr22_whole")
    parser.add_argument("--h1sq", nargs="+", type=float, default=None)
    parser.add_argument("--h2sq", nargs="+", type=float, default=None)
    parser.add_argument("--gc", nargs="+", type=float, default=None)
    parser.add_argument("--n1", nargs="+", type=int, default=None)
    parser.add_argument("--n2", nargs="+", type=int, default=None)
    parser.add_argument("--nt", nargs="+", type=int, default=None)
    parser.add_argument("--propt", nargs="+", type=float, default=None)
    parser.add_argument("--pcausal", nargs="+", type=float, default=None)
    parser.add_argument("--nrep", type=int, default=1)
    parser.add_argument("--seed", type=int, default=20260429)
    parser.add_argument(
        "--architecture_probs",
        type=float,
        nargs=4,
        default=DEFAULT_ARCHITECTURE_PROBS,
        metavar=("SHARED", "POP1_SPECIFIC", "POP2_SPECIFIC", "NULL"),
        help=(
            "Gene architecture proportions, in order: shared pop1_specific "
            "pop2_specific null."
        ),
    )
    parser.add_argument(
        "--architecture_seed",
        type=int,
        default=20260430,
        help="Seed for reproducible gene architecture assignment.",
    )
    parser.add_argument(
        "--estimate_omega",
        action="store_true",
        default=None,
        help="Estimate omega by LDSC. Default uses the true simulated omega.",
    )
    parser.add_argument(
        "--no_estimate_omega",
        action="store_false",
        dest="estimate_omega",
        help="Use the true simulated omega instead of LDSC-estimated omega.",
    )
    parser.add_argument(
        "--omega_p_threshold",
        type=float,
        default=DEFAULT_OMEGA_P_THRESHOLD,
        help="P-value gate for estimated omega runs.",
    )
    parser.add_argument(
        "--min_snps_per_gene",
        type=int,
        default=5,
        help="Skip genes with fewer annotated SNPs.",
    )
    parser.add_argument(
        "--max_snps_per_gene",
        type=int,
        default=None,
        help="Subsample SNPs when a gene has more SNPs than this. Use 0 for no cap.",
    )
    parser.add_argument(
        "--max_genes",
        type=int,
        default=0,
        help="For smoke tests, stop after this many eligible genes. 0 means all genes.",
    )
    parser.add_argument(
        "--include_intergenic_nearest",
        action="store_true",
        help="Include SNPs assigned to nearest genes even when outside gene bodies.",
    )
    parser.add_argument(
        "--out_dir",
        default=None,
        help="Output directory.",
    )
    parser.add_argument(
        "--target_null_alpha",
        action="store_true",
        help=(
            "Summarize alpha as an all-SNP false positive rate, matching "
            "visual_simulation.py alpha runs. Automatically enabled when h1sq <= 1e-8."
        ),
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Print generated setting names without running simulations.",
    )
    args = parser.parse_args(argv)
    return finalize_parsed_args(args)


def _grid_values(args: argparse.Namespace, name: str) -> list:
    value = getattr(args, name)
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _has_explicit_multi_grid(args: argparse.Namespace) -> bool:
    return any(len(_grid_values(args, name)) > 1 for name in GRID_PARAMETER_NAMES)


def finalize_parsed_args(args: argparse.Namespace) -> argparse.Namespace:
    grid_requested = bool(
        args.run_prefix or args.dry_run or _has_explicit_multi_grid(args)
    )
    value_defaults = MIXTURE_GRID_DEFAULTS if grid_requested else SINGLE_GRID_DEFAULTS
    for name, default in value_defaults.items():
        if getattr(args, name) is None:
            setattr(args, name, list(default))

    if grid_requested:
        for name, default in MIXTURE_INPUT_DEFAULTS.items():
            if getattr(args, name) is None:
                setattr(args, name, default)
    if args.out_dir is None:
        args.out_dir = (
            "bench/result/chr22_eqtl_mixture" if grid_requested else "bench/result"
        )
    if args.max_snps_per_gene is None:
        args.max_snps_per_gene = 0 if grid_requested else 1000
    if args.estimate_omega is None:
        args.estimate_omega = grid_requested
    return args


def should_use_grid_runname(args: argparse.Namespace) -> bool:
    return bool(args.run_prefix or args.dry_run or _has_explicit_multi_grid(args))


def should_run_grid(args: argparse.Namespace) -> bool:
    return should_use_grid_runname(args)


def fmt(value: float | int) -> str:
    return f"{value:g}" if isinstance(value, float) else str(value)


def build_grid_runname(
    run_prefix: str,
    h1sq: float,
    h2sq: float,
    gc: float,
    n1: int,
    n2: int,
    nt: int,
    propt: float,
    pcausal: float,
    estimate_omega: bool,
) -> str:
    return (
        f"{run_prefix}_h1sq_{fmt(h1sq)}_h2sq_{fmt(h2sq)}_gc_{fmt(gc)}"
        f"_n1_{n1}_n2_{n2}_nt_{nt}_propt_{fmt(propt)}"
        f"_pcausal_{fmt(pcausal)}_omega_{not estimate_omega}"
    )


def build_setting_args(
    args: argparse.Namespace,
    h1sq: float,
    h2sq: float,
    gc: float,
    n1: int,
    n2: int,
    nt: int,
    propt: float,
    pcausal: float,
) -> argparse.Namespace:
    setting_args = argparse.Namespace(**vars(args))
    setting_args.h1sq = h1sq
    setting_args.h2sq = h2sq
    setting_args.gc = gc
    setting_args.n1 = n1
    setting_args.n2 = n2
    setting_args.nt = nt
    setting_args.pop2_sample_start = n1
    setting_args.pop2_tissue_start = None
    setting_args.propt = propt
    setting_args.pcausal = pcausal
    if should_use_grid_runname(args):
        setting_args.runname = build_grid_runname(
            args.run_prefix or args.runname,
            h1sq,
            h2sq,
            gc,
            n1,
            n2,
            nt,
            propt,
            pcausal,
            args.estimate_omega,
        )
    return setting_args


def iter_setting_args(args: argparse.Namespace):
    h1sq = _grid_values(args, "h1sq")
    h2sq = _grid_values(args, "h2sq")
    gc = _grid_values(args, "gc")
    n1 = _grid_values(args, "n1")
    n2 = _grid_values(args, "n2")
    nt = _grid_values(args, "nt")
    propt = _grid_values(args, "propt")
    pcausal = _grid_values(args, "pcausal")
    for h1sqi, h2sqj, gck, n1l, n2m, ntn, proptp, pcausalq in itertools.product(
        h1sq, h2sq, gc, n1, n2, nt, propt, pcausal
    ):
        yield build_setting_args(
            args,
            h1sqi,
            h2sqj,
            gck,
            n1l,
            n2m,
            ntn,
            proptp,
            pcausalq,
        )


def iter_grid_run_args(args: argparse.Namespace):
    return iter_setting_args(args)


def scalarize_single_args(args: argparse.Namespace) -> argparse.Namespace:
    return next(iter_setting_args(args))


def read_fam_count(prefix: str | Path) -> int:
    fam_path = Path(f"{prefix}.fam")
    with fam_path.open() as handle:
        return sum(1 for _ in handle)


def read_bim_rows(prefix: str | Path) -> list[dict[str, str | int | float]]:
    bim_path = Path(f"{prefix}.bim")
    rows: list[dict[str, str | int | float]] = []
    with bim_path.open() as handle:
        for idx, line in enumerate(handle):
            fields = line.split()
            if len(fields) < 6:
                continue
            rows.append(
                {
                    "snp_index": idx,
                    "chr": fields[0].replace("chr", ""),
                    "snp": fields[1],
                    "cm": float(fields[2]),
                    "bp": int(fields[3]),
                    "a1": fields[4],
                    "a2": fields[5],
                }
            )
    return rows


def read_snp_set(path: str | Path | None) -> set[str]:
    if path is None:
        return set()
    with Path(path).open() as handle:
        return {line.strip() for line in handle if line.strip()}


def load_snp_gene(path: str | Path, include_intergenic_nearest: bool) -> list[dict]:
    rows: list[dict] = []
    with Path(path).open() as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        for row in reader:
            if (
                "is_gene_body" in row
                and not include_intergenic_nearest
                and int(row["is_gene_body"]) == 0
            ):
                continue
            if "snp_index" not in row:
                row["snp_index"] = row.get("pop1_idx", row.get("pop2_idx"))
            row["snp_index"] = int(row["snp_index"])
            if "pop1_idx" in row:
                row["pop1_idx"] = int(row["pop1_idx"])
            else:
                row["pop1_idx"] = row["snp_index"]
            if "pop2_idx" in row:
                row["pop2_idx"] = int(row["pop2_idx"])
            else:
                row["pop2_idx"] = row["snp_index"]
            row["bp"] = int(row["bp"])
            row["gene_start"] = int(row["gene_start"])
            row["gene_end"] = int(row["gene_end"])
            if "window_start" in row:
                row["window_start"] = int(row["window_start"])
            else:
                row["window_start"] = row["gene_start"]
            if "window_end" in row:
                row["window_end"] = int(row["window_end"])
            else:
                row["window_end"] = row["gene_end"]
            rows.append(row)
    return rows


def group_snp_gene_rows(rows: list[dict]) -> list[tuple[str, list[dict]]]:
    groups: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        groups[row["gene_id"]].append(row)
    grouped = sorted(
        groups.items(),
        key=lambda item: (
            int(item[1][0]["gene_start"]),
            int(item[1][0]["gene_end"]),
            item[0],
        ),
    )
    return grouped


def assign_gene_architectures(
    groups: list[tuple[str, list[dict]]],
    probs: tuple[float, float, float, float] | list[float],
    seed: int,
) -> dict[str, str]:
    probs_arr = np.asarray(probs, dtype=float)
    if probs_arr.shape != (len(ARCHITECTURES),):
        raise ValueError(
            f"--architecture_probs must have {len(ARCHITECTURES)} values: "
            + " ".join(ARCHITECTURES)
        )
    if np.any(probs_arr < 0) or probs_arr.sum() <= 0:
        raise ValueError("--architecture_probs must be non-negative and sum to > 0.")
    probs_arr = probs_arr / probs_arr.sum()

    rng = np.random.default_rng(seed)
    assigned = rng.choice(ARCHITECTURES, size=len(groups), p=probs_arr)
    return {
        str(gene_id): str(architecture)
        for (gene_id, _rows), architecture in zip(groups, assigned, strict=True)
    }


class PlinkBedReader:
    """Minimal SNP-major PLINK .bed reader for selected SNP/sample subsets."""

    def __init__(self, prefix: str | Path):
        self.prefix = Path(prefix)
        self.n_samples = read_fam_count(self.prefix)
        self.n_snps = len(read_bim_rows(self.prefix))
        self.bytes_per_snp = (self.n_samples + 3) // 4
        self.bed_path = Path(f"{self.prefix}.bed")
        self.handle = self.bed_path.open("rb")
        magic = self.handle.read(3)
        if magic != b"\x6c\x1b\x01":
            raise ValueError(
                f"{self.bed_path} is not SNP-major PLINK .bed; header={magic!r}"
            )

    def close(self) -> None:
        self.handle.close()

    def read(self, snp_indices: np.ndarray, sample_indices: np.ndarray) -> np.ndarray:
        geno = np.empty((len(sample_indices), len(snp_indices)), dtype=np.float64)
        sample_indices = np.asarray(sample_indices, dtype=np.int64)
        sample_byte_idx = sample_indices // 4
        sample_shift = (sample_indices % 4) * 2
        for out_j, snp_idx in enumerate(snp_indices):
            self.handle.seek(3 + int(snp_idx) * self.bytes_per_snp)
            raw = np.frombuffer(self.handle.read(self.bytes_per_snp), dtype=np.uint8)
            codes = (raw[sample_byte_idx].astype(np.uint8) >> sample_shift) & 0b11
            col = np.empty(len(sample_indices), dtype=np.float64)
            col[codes == 0b00] = 0.0
            col[codes == 0b10] = 1.0
            col[codes == 0b11] = 2.0
            col[codes == 0b01] = BED_MISSING
            if np.isnan(col).any():
                mean = np.nanmean(col)
                col = np.where(np.isnan(col), 0.0 if np.isnan(mean) else mean, col)
            geno[:, out_j] = col
        return geno


class SldxrGeneLD:
    def __init__(
        self, pop1_path: str | Path, pop2_path: str | Path, cross_path: str | Path
    ):
        self.pop1 = pd.read_table(pop1_path)
        self.pop2 = pd.read_table(pop2_path)
        self.cross = pd.read_table(cross_path)
        self.snp_to_row = {
            snp: idx for idx, snp in enumerate(self.pop1["SNP"].astype(str).to_numpy())
        }
        self.gene_cols = set(self.pop1.columns[3:])

    def get(
        self, gene_id: str, snps: list[str]
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if gene_id not in self.gene_cols:
            raise KeyError(f"{gene_id} not found in s-ldxr LD score columns.")
        row_idx = [self.snp_to_row[snp] for snp in snps]
        ld1 = self.pop1.iloc[row_idx][gene_id].to_numpy(dtype=np.float64)
        ld2 = self.pop2.iloc[row_idx][gene_id].to_numpy(dtype=np.float64)
        ldx = self.cross.iloc[row_idx][gene_id].to_numpy(dtype=np.float64)
        return ld1, ld2, ldx


def standardize_genotype(geno: np.ndarray) -> np.ndarray:
    mean = np.mean(geno, axis=0)
    std = np.std(geno, axis=0)
    return (geno - mean) / (std + MIN_FLOAT)


def tail_panel_start(
    n_rows: int, n_singlecell: int, n_tissue: int, panel_name: str
) -> int:
    if n_singlecell < 0 or n_tissue < 0:
        raise ValueError(f"{panel_name} sample sizes must be nonnegative")
    if n_singlecell > n_rows:
        raise ValueError(
            f"single-cell n={n_singlecell} exceeds {panel_name} rows={n_rows}"
        )
    if n_tissue > n_rows:
        raise ValueError(f"tissue n={n_tissue} exceeds {panel_name} rows={n_rows}")
    start = n_rows - n_tissue
    if start < n_singlecell:
        raise ValueError(
            f"{panel_name} tail tissue panel overlaps prefix single-cell panel: "
            f"n_singlecell={n_singlecell}, n_tissue={n_tissue}, rows={n_rows}"
        )
    return start


def make_component_rng(
    seed_base: int | None,
    seed_parts: tuple,
    component: str,
    fallback_rng: np.random.Generator,
) -> np.random.Generator:
    if seed_base is None:
        return fallback_rng
    tokens = []
    for part in (component, *seed_parts):
        if isinstance(part, float):
            tokens.append(f"{part:.17g}")
        else:
            tokens.append(str(part))
    seed_key = "|".join([str(int(seed_base)), *tokens])
    seed = int.from_bytes(
        hashlib.blake2s(seed_key.encode("utf-8"), digest_size=8).digest(),
        "little",
    )
    return np.random.default_rng(seed)


def calculate_sumstats(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    n = x.shape[0]
    x_inner = np.sum(x * x, axis=0) + MIN_FLOAT
    xy = x.T @ y
    beta_hat = xy / x_inner
    y_inner = float(y @ y)
    sse = y_inner - 2 * beta_hat * xy + beta_hat * beta_hat * x_inner
    sse = np.maximum(sse, MIN_FLOAT)
    se_hat = np.sqrt(sse / (n * x_inner))
    return beta_hat, se_hat


def calculate_ld_scores(
    x1: np.ndarray, x2: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    cor1 = np.corrcoef(x1, rowvar=False)
    cor2 = np.corrcoef(x2, rowvar=False)
    cor1 = np.nan_to_num(cor1, nan=0.0, posinf=0.0, neginf=0.0)
    cor2 = np.nan_to_num(cor2, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(cor1, 1.0)
    np.fill_diagonal(cor2, 1.0)
    ld1 = np.sum(cor1 * cor1, axis=0)
    ld2 = np.sum(cor2 * cor2, axis=0)
    ldx = np.sum(cor1 * cor2, axis=0)
    return ld1, ld2, ldx


def clip_correlation(var1: float, var2: float, cov: float) -> tuple[float, float]:
    denominator = math.sqrt(max(var1, 0.0)) * math.sqrt(max(var2, 0.0)) + MIN_FLOAT
    cor = cov / denominator
    if abs(cor) > MAX_CORR:
        cor = math.copysign(MAX_CORR, cor)
        cov = cor * denominator
    return float(cov), float(cor)


def has_tissue_genetic_effect(architecture: str) -> bool:
    if architecture not in ARCHITECTURES:
        raise ValueError(f"Unknown architecture: {architecture}")
    return architecture in {"shared", "pop2_specific"}


def generate_data(
    g1: np.ndarray,
    g2: np.ndarray,
    architecture: str,
    h1sq: float,
    h2sq: float,
    gc: float,
    n1: int,
    n2: int,
    nt: int,
    propt: float,
    pcausal: float,
    rng: np.random.Generator,
    tissue_start: int | None = None,
    seed_base: int | None = None,
    seed_parts: tuple = (),
) -> tuple:
    nsnp = g1.shape[1]
    if tissue_start is None:
        tissue_start = tail_panel_start(g2.shape[0], n2, nt, "population 2")
    if n1 > g1.shape[0]:
        raise ValueError(f"n1={n1} exceeds population 1 genotype rows={g1.shape[0]}")
    if n2 > g2.shape[0]:
        raise ValueError(f"n2={n2} exceeds population 2 genotype rows={g2.shape[0]}")
    if tissue_start < n2:
        raise ValueError(
            f"tissue_start={tissue_start} must be >= n2={n2} to keep panels disjoint"
        )
    if tissue_start + nt > g2.shape[0]:
        raise ValueError(
            f"tissue_start + nt = {tissue_start + nt} exceeds "
            f"population 2 genotype rows={g2.shape[0]}"
        )

    x1 = standardize_genotype(g1[:n1, :])
    x2 = standardize_genotype(g2[:n2, :])
    xt = standardize_genotype(g2[tissue_start : tissue_start + nt, :])

    causal_mass = pcausal * nsnp
    num_causal = int(causal_mass)
    causal_id_rng = make_component_rng(seed_base, seed_parts, "causal_ids", rng)
    causal_ids = (
        causal_id_rng.choice(np.arange(nsnp), num_causal, replace=False)
        if num_causal > 0
        else np.array([], dtype=int)
    )
    omega_causal = np.array(
        [[h1sq, math.sqrt(h1sq * h2sq) * gc], [math.sqrt(h1sq * h2sq) * gc, h2sq]]
    )
    beta1 = np.zeros(nsnp)
    beta2 = np.zeros(nsnp)
    causal_ids_pop1 = np.array([], dtype=int)
    causal_ids_pop2 = np.array([], dtype=int)

    if architecture not in ARCHITECTURES:
        raise ValueError(f"Unknown architecture: {architecture}")
    effect_rng = make_component_rng(seed_base, seed_parts, "causal_effects", rng)
    if num_causal > 0 and architecture == "shared":
        beta_causal = effect_rng.multivariate_normal(
            mean=np.zeros(2), cov=omega_causal / causal_mass, size=num_causal
        )
        beta1[causal_ids] = beta_causal[:, 0]
        beta2[causal_ids] = beta_causal[:, 1]
        causal_ids_pop1 = causal_ids
        causal_ids_pop2 = causal_ids
    elif num_causal > 0 and architecture == "pop1_specific":
        beta1[causal_ids] = effect_rng.normal(
            loc=0.0, scale=math.sqrt(h1sq / causal_mass), size=num_causal
        )
        causal_ids_pop1 = causal_ids
    elif num_causal > 0 and architecture == "pop2_specific":
        beta2[causal_ids] = effect_rng.normal(
            loc=0.0, scale=math.sqrt(h2sq / causal_mass), size=num_causal
        )
        causal_ids_pop2 = causal_ids

    y1_noise_var = 1 - h1sq if causal_ids_pop1.size else 1.0
    y2_noise_var = 1 - h2sq if causal_ids_pop2.size else 1.0
    pop1_noise_rng = make_component_rng(seed_base, seed_parts, "pop1_noise", rng)
    pop2_noise_rng = make_component_rng(seed_base, seed_parts, "pop2_noise", rng)
    y1 = x1 @ beta1 + math.sqrt(max(y1_noise_var, MIN_FLOAT)) * pop1_noise_rng.normal(size=n1)
    y2 = x2 @ beta2 + math.sqrt(max(y2_noise_var, MIN_FLOAT)) * pop2_noise_rng.normal(size=n2)

    delta = 5
    pi_rng = make_component_rng(seed_base, seed_parts, "cell_proportion", rng)
    if tissue_start + nt == g2.shape[0]:
        pi_all = pi_rng.beta(
            propt * delta, (1 - propt + MIN_FLOAT) * delta, g2.shape[0]
        )
        pi_ind = pi_all[tissue_start : tissue_start + nt]
    else:
        pi_ind = pi_rng.beta(propt * delta, (1 - propt + MIN_FLOAT) * delta, nt)
    pi_mean = float(np.mean(pi_ind))
    beta_unknown = np.zeros(nsnp)
    tissue_has_effect = has_tissue_genetic_effect(architecture)
    if num_causal > 0 and tissue_has_effect:
        unknown_id_rng = make_component_rng(seed_base, seed_parts, "unknown_ids", rng)
        unknown_effect_rng = make_component_rng(
            seed_base, seed_parts, "unknown_effects", rng
        )
        unknown_ids = unknown_id_rng.choice(np.arange(nsnp), num_causal, replace=False)
        beta_unknown[unknown_ids] = unknown_effect_rng.normal(
            loc=0.0, scale=math.sqrt(h2sq / causal_mass), size=num_causal
        )
    tissue_hsq = h2sq if tissue_has_effect else 0.0
    tissue_noise_var = 1 - (pi_ind**2 + (1 - pi_ind) ** 2) * tissue_hsq
    tissue_noise_rng = make_component_rng(seed_base, seed_parts, "tissue_noise", rng)
    if tissue_start + nt == g2.shape[0]:
        tissue_noise = tissue_noise_rng.normal(size=g2.shape[0])[
            tissue_start : tissue_start + nt
        ]
    else:
        tissue_noise = tissue_noise_rng.normal(size=nt)
    yt = (
        pi_ind * (xt @ beta2)
        + (1 - pi_ind) * (xt @ beta_unknown)
        + np.sqrt(np.maximum(tissue_noise_var, MIN_FLOAT)) * tissue_noise
    )

    b1_hat, se1_hat = calculate_sumstats(x1, y1)
    b2_hat, se2_hat = calculate_sumstats(x2, y2)
    bt_hat, se_t_hat = calculate_sumstats(xt, yt)
    omega_true = np.cov(
        np.stack([beta1, beta2, beta2 * pi_mean + beta_unknown * (1 - pi_mean)])
    )
    return (
        omega_true,
        b1_hat,
        se1_hat,
        b2_hat,
        se2_hat,
        bt_hat,
        se_t_hat,
        causal_ids_pop1,
        causal_ids_pop2,
        pi_mean,
        x1,
        x2,
    )


def re2_meta(betas: np.ndarray, ses: np.ndarray) -> tuple[float, float]:
    variances = ses * ses
    tau2 = 0.0
    weights = 1.0 / (variances + MIN_FLOAT)
    combined_beta = float(np.sum(weights * betas) / np.sum(weights))
    for _ in range(100):
        denom = variances + tau2 + MIN_FLOAT
        weights = 1.0 / denom
        new_beta = float(np.sum(betas * weights) / np.sum(weights))
        numerator = np.sum(((betas - new_beta) ** 2 - variances) / (denom * denom))
        denominator = np.sum(1.0 / (denom * denom))
        new_tau2 = float(numerator / (denominator + MIN_FLOAT))
        if new_tau2 < 0:
            tau2 = 0.0
            break
        if max(abs(new_beta - combined_beta), abs(new_tau2 - tau2)) < 1e-6:
            combined_beta = new_beta
            tau2 = new_tau2
            break
        combined_beta = new_beta
        tau2 = new_tau2
    weights = 1.0 / (variances + tau2 + MIN_FLOAT)
    beta = float(np.sum(betas * weights) / np.sum(weights))
    se = math.sqrt(float(1.0 / np.sum(weights)))
    return beta, se


def estimate_omega(
    b1_hat: np.ndarray,
    se1_hat: np.ndarray,
    b2_hat: np.ndarray,
    se2_hat: np.ndarray,
    bt_hat: np.ndarray,
    se_t_hat: np.ndarray,
    ld1: np.ndarray,
    ld2: np.ndarray,
    ldx: np.ndarray,
    n1: int,
    n2: int,
    nt: int,
    propt: float,
    threshold: float,
) -> tuple[np.ndarray, float, bool, bool]:
    if len(ld1) < 10:
        return np.eye(2) * MIN_HERITABILITY, MIN_HERITABILITY, False, False
    omega, omega_se = Run_Cross_LDSC(
        b1_hat / se1_hat,
        np.full(len(ld1), n1),
        ld1,
        b2_hat / se2_hat,
        np.full(len(ld1), n2),
        ld2,
        ldx,
        np.array([1.0, 1.0, 0.0]),
    )
    omega_p = z2p(omega / (omega_se + MIN_FLOAT))
    run_gmm = bool(np.all(omega_p < threshold))
    if not run_gmm:
        return omega, MIN_HERITABILITY, False, False
    omega[0, 1], _ = clip_correlation(omega[0, 0], omega[1, 1], omega[0, 1])
    omega[1, 0] = omega[0, 1]

    aux_omega, aux_omega_se = Run_Cross_LDSC(
        b2_hat / se2_hat,
        np.full(len(ld1), n2),
        ld2,
        bt_hat / se_t_hat,
        np.full(len(ld1), nt),
        ld2,
        ld2,
        np.array([1.0, 1.0, 0.0]),
    )
    aux_omega[0, 1], _ = clip_correlation(
        aux_omega[0, 0], aux_omega[1, 1], aux_omega[0, 1]
    )
    aux_omega[1, 0] = aux_omega[0, 1]
    aux_p = z2p(aux_omega / (aux_omega_se + MIN_FLOAT))
    run_gmm_tissue = bool(np.all(aux_p < threshold))
    pi2_omega_sum = (
        aux_omega[1, 1]
        - propt**2 * omega[1, 1]
        - 2 * propt * np.maximum(aux_omega[0, 1] - propt * omega[1, 1], 0)
    )
    if pi2_omega_sum < 0:
        run_gmm_tissue = False
    return omega, float(pi2_omega_sum), run_gmm, run_gmm_tissue


def run_methods(
    omega_true: np.ndarray,
    b1_hat: np.ndarray,
    se1_hat: np.ndarray,
    b2_hat: np.ndarray,
    se2_hat: np.ndarray,
    bt_hat: np.ndarray,
    se_t_hat: np.ndarray,
    ld1: np.ndarray,
    ld2: np.ndarray,
    ldx: np.ndarray,
    n1: int,
    n2: int,
    nt: int,
    propt: float,
    estimate: bool,
    omega_p_threshold: float,
) -> dict[str, np.ndarray | float | bool]:
    nsnp = len(b1_hat)
    if estimate:
        omega, pi2_omega_sum, run_gmm, run_gmm_tissue = estimate_omega(
            b1_hat,
            se1_hat,
            b2_hat,
            se2_hat,
            bt_hat,
            se_t_hat,
            ld1,
            ld2,
            ldx,
            n1,
            n2,
            nt,
            propt,
            omega_p_threshold,
        )
    else:
        omega = omega_true[:2, :2]
        run_gmm = True
        run_gmm_tissue = True
        pi2_omega_sum = (
            omega_true[2, 2]
            - propt**2 * omega_true[1, 1]
            - 2 * propt * (omega_true[1, 2] - propt * omega_true[1, 1])
        )
        pi2_omega_sum = max(float(pi2_omega_sum), MIN_HERITABILITY)

    pop1_z = np.zeros((nsnp, 3))
    pop2_z = np.zeros((nsnp, 3))
    meta_z = np.zeros(nsnp)
    meta_tissue_z = np.zeros(nsnp)
    eye2 = np.eye(2)
    eye3 = np.eye(3)

    for j in range(nsnp):
        pop1_z[j, 0] = b1_hat[j] / se1_hat[j]
        pop2_z[j, 0] = b2_hat[j] / se2_hat[j]
        if run_gmm:
            try:
                b1_c, se1_c, b2_c, se2_c = GMM(
                    omega,
                    eye2,
                    b1_hat[j],
                    se1_hat[j],
                    ld1[j],
                    b2_hat[j],
                    se2_hat[j],
                    ld2[j],
                    ldx[j],
                )
                pop1_z[j, 1] = b1_c / se1_c
                pop2_z[j, 1] = b2_c / se2_c
            except Exception:
                pop1_z[j, 1] = pop1_z[j, 0]
                pop2_z[j, 1] = pop2_z[j, 0]
        else:
            pop1_z[j, 1] = pop1_z[j, 0]
            pop2_z[j, 1] = pop2_z[j, 0]

        if run_gmm_tissue:
            try:
                b1_t, se1_t, b2_t, se2_t = GMMtissue(
                    omega,
                    eye3,
                    b1_hat[j],
                    se1_hat[j],
                    ld1[j],
                    b2_hat[j],
                    se2_hat[j],
                    ld2[j],
                    ldx[j],
                    bt_hat[j],
                    se_t_hat[j],
                    pi2_omega_sum,
                    propt,
                )
                pop1_z[j, 2] = b1_t / se1_t
                pop2_z[j, 2] = b2_t / se2_t
            except Exception:
                pop1_z[j, 2] = pop1_z[j, 1]
                pop2_z[j, 2] = pop2_z[j, 1]
        else:
            pop1_z[j, 2] = pop1_z[j, 1]
            pop2_z[j, 2] = pop2_z[j, 1]

        mb, ms = re2_meta(
            np.array([b1_hat[j], b2_hat[j]]),
            np.array([se1_hat[j], se2_hat[j]]),
        )
        mtb, mts = re2_meta(
            np.array([b1_hat[j], b2_hat[j], bt_hat[j]]),
            np.array([se1_hat[j], se2_hat[j], se_t_hat[j]]),
        )
        meta_z[j] = mb / ms
        meta_tissue_z[j] = mtb / mts

    return {
        "pop1_z": pop1_z,
        "pop2_z": pop2_z,
        "zt": bt_hat / se_t_hat,
        "meta_z": meta_z,
        "meta_tissue_z": meta_tissue_z,
        "run_gmm": run_gmm,
        "run_gmm_tissue": run_gmm_tissue,
        "pi2_omega_sum": pi2_omega_sum,
    }


def select_gene_snps(
    rows: list[dict],
    max_snps_per_gene: int,
    rng: np.random.Generator,
) -> list[dict]:
    if max_snps_per_gene <= 0 or len(rows) <= max_snps_per_gene:
        return rows
    idx = np.sort(rng.choice(np.arange(len(rows)), max_snps_per_gene, replace=False))
    return [rows[i] for i in idx]


def open_text_gz(path: Path):
    if path.suffix == ".gz":
        return gzip.open(path, "wt", newline="")
    return path.open("w", newline="")


def write_rows(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open_text_gz(path) as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def append_rows(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    if not rows:
        return
    exists = path.exists()
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "at" if path.suffix == ".gz" else "a"
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, mode, newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        if not exists:
            writer.writeheader()
        writer.writerows(rows)


def summarize_gene_snp_counts(groups: list[tuple[str, list[dict]]]) -> list[dict]:
    return [
        {
            "gene_id": gene_id,
            "gene_name": rows[0]["gene_name"],
            "gene_type": rows[0]["gene_type"],
            "nsnp_gene": len(rows),
        }
        for gene_id, rows in groups
    ]


def print_gene_snp_count_summary(rows: list[dict]) -> None:
    counts = np.array([row["nsnp_gene"] for row in rows], dtype=float)
    print(
        "Gene SNP counts: "
        f"n_gene={len(rows)}, "
        f"min={int(np.min(counts))}, "
        f"median={float(np.median(counts)):.1f}, "
        f"mean={float(np.mean(counts)):.1f}, "
        f"max={int(np.max(counts))}"
    )


def run_single_simulation(args: argparse.Namespace) -> None:
    started = time.time()

    pop1_prefix = args.pop1_plink_prefix or args.plink_prefix
    pop2_prefix = args.pop2_plink_prefix or args.plink_prefix
    one_prefix = Path(pop1_prefix).resolve() == Path(pop2_prefix).resolve()

    annot_rows = load_snp_gene(args.snp_gene, args.include_intergenic_nearest)
    groups = group_snp_gene_rows(annot_rows)
    groups = [
        (gene_id, rows)
        for gene_id, rows in groups
        if len(rows) >= args.min_snps_per_gene
    ]
    if args.max_genes > 0:
        groups = groups[: args.max_genes]
    if not groups:
        raise ValueError("No eligible genes after annotation filters.")
    architecture_map = assign_gene_architectures(
        groups, args.architecture_probs, args.architecture_seed
    )

    pop1_reader = PlinkBedReader(pop1_prefix)
    pop2_reader = pop1_reader if one_prefix else PlinkBedReader(pop2_prefix)
    pop2_flip_snps = read_snp_set(args.pop2_flip_snps)
    ld_scores = None
    if not args.use_sample_ld:
        if args.ld_pop1 and args.ld_pop2 and args.ld_cross:
            print("Loading s-ldxr gene LD scores")
            ld_scores = SldxrGeneLD(args.ld_pop1, args.ld_pop2, args.ld_cross)
        else:
            print("No complete s-ldxr LD score paths supplied; using sample LD.")
    out_dir = Path(args.out_dir) / args.runname
    out_dir.mkdir(parents=True, exist_ok=True)
    gene_snp_count_rows = summarize_gene_snp_counts(groups)
    gene_snp_count_path = out_dir / "gene_snp_counts.csv"
    write_rows(
        gene_snp_count_path,
        gene_snp_count_rows,
        ["gene_id", "gene_name", "gene_type", "nsnp_gene"],
    )
    architecture_path = out_dir / "gene_architecture.tsv"
    with architecture_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["gene_id", "gene_name", "architecture"],
            delimiter="\t",
        )
        writer.writeheader()
        for gene_id, rows in groups:
            writer.writerow(
                {
                    "gene_id": gene_id,
                    "gene_name": rows[0]["gene_name"],
                    "architecture": architecture_map[gene_id],
                }
            )

    result_path = out_dir / "snp_results.csv.gz"
    summary_path = out_dir / "gene_summary.csv"
    for path in (result_path, summary_path):
        if path.exists():
            path.unlink()
    result_fields = [
        "rep",
        "gene_id",
        "gene_name",
        "gene_type",
        "architecture",
        "chr",
        "snp",
        "bp",
        "a1",
        "a2",
        "snp_index",
        "nsnp_gene",
        "causal",
        "causal_pop1",
        "causal_pop2",
        "z1_sumstat",
        "z1_cross",
        "z1_tissue",
        "z2_sumstat",
        "z2_cross",
        "z2_tissue",
        "zt_sumstat",
        "z_meta",
        "z_metatissue",
        "pi_mean",
        "run_gmm",
        "run_gmm_tissue",
    ]
    summary_rows: list[dict] = []

    pop2_sample_start = getattr(args, "pop2_sample_start", args.n1)
    pop2_tissue_start = args.n2
    if one_prefix:
        pop2_sc_end = pop2_sample_start + args.n2
        physical_tissue_start = tail_panel_start(
            pop1_reader.n_samples, pop2_sc_end, args.nt, "shared PLINK"
        )
        if pop1_reader.n_samples < args.n1:
            raise ValueError(f"pop1 has fewer than n1={args.n1} samples.")
        if pop2_sample_start < args.n1:
            raise ValueError(
                "pop2_sample_start must be >= n1 when one PLINK prefix is split."
            )
        pop1_samples = np.arange(args.n1)
        pop2_samples = np.concatenate(
            [
                np.arange(pop2_sample_start, pop2_sc_end),
                np.arange(physical_tissue_start, pop1_reader.n_samples),
            ]
        )
    else:
        if pop1_reader.n_samples < args.n1:
            raise ValueError(f"pop1 has fewer than n1={args.n1} samples.")
        physical_tissue_start = tail_panel_start(
            pop2_reader.n_samples, args.n2, args.nt, "population 2"
        )
        pop1_samples = np.arange(args.n1)
        pop2_samples = np.concatenate(
            [np.arange(args.n2), np.arange(physical_tissue_start, pop2_reader.n_samples)]
        )

    print(
        f"Running {len(groups)} genes, n1={args.n1}, n2={args.n2}, nt={args.nt}, "
        f"nrep={args.nrep}, one_prefix={one_prefix}"
    )
    for rep in range(args.nrep):
        rep_rng = make_component_rng(
            args.seed,
            (rep,),
            "gene_selection",
            np.random.default_rng(args.seed + rep),
        )
        for gene_i, (gene_id, raw_gene_rows) in enumerate(groups, start=1):
            architecture = architecture_map[gene_id]
            gene_rows = select_gene_snps(raw_gene_rows, args.max_snps_per_gene, rep_rng)
            pop1_snp_indices = np.array(
                [row["pop1_idx"] for row in gene_rows], dtype=int
            )
            pop2_snp_indices = np.array(
                [row["pop2_idx"] for row in gene_rows], dtype=int
            )
            g1 = pop1_reader.read(pop1_snp_indices, pop1_samples)
            g2 = pop2_reader.read(pop2_snp_indices, pop2_samples)
            if pop2_flip_snps:
                flip_cols = [
                    j for j, row in enumerate(gene_rows) if row["snp"] in pop2_flip_snps
                ]
                if flip_cols:
                    g2[:, flip_cols] = 2.0 - g2[:, flip_cols]
            (
                omega_true,
                b1_hat,
                se1_hat,
                b2_hat,
                se2_hat,
                bt_hat,
                se_t_hat,
                causal_ids_pop1,
                causal_ids_pop2,
                pi_mean,
                x1,
                x2,
            ) = generate_data(
                g1,
                g2,
                architecture,
                args.h1sq,
                args.h2sq,
                args.gc,
                args.n1,
                args.n2,
                args.nt,
                args.propt,
                args.pcausal,
                rep_rng,
                tissue_start=pop2_tissue_start,
                seed_base=args.seed,
                seed_parts=(rep, gene_id),
            )
            if ld_scores is not None:
                ld1, ld2, ldx = ld_scores.get(
                    gene_id, [row["snp"] for row in gene_rows]
                )
            else:
                ld1, ld2, ldx = calculate_ld_scores(x1, x2)
            method = run_methods(
                omega_true,
                b1_hat,
                se1_hat,
                b2_hat,
                se2_hat,
                bt_hat,
                se_t_hat,
                ld1,
                ld2,
                ldx,
                args.n1,
                args.n2,
                args.nt,
                args.propt,
                args.estimate_omega,
                args.omega_p_threshold,
            )
            causal_pop1 = np.zeros(len(gene_rows), dtype=bool)
            causal_pop2 = np.zeros(len(gene_rows), dtype=bool)
            causal_pop1[causal_ids_pop1] = True
            causal_pop2[causal_ids_pop2] = True
            pop1_z = method["pop1_z"]
            pop2_z = method["pop2_z"]

            out_rows = []
            for j, row in enumerate(gene_rows):
                out_rows.append(
                    {
                        "rep": rep,
                        "gene_id": gene_id,
                        "gene_name": row["gene_name"],
                        "gene_type": row["gene_type"],
                        "architecture": architecture,
                        "chr": row["chr"],
                        "snp": row["snp"],
                        "bp": row["bp"],
                        "a1": row["a1"],
                        "a2": row["a2"],
                        "snp_index": row["snp_index"],
                        "nsnp_gene": len(gene_rows),
                        "causal": int(causal_pop1[j]),
                        "causal_pop1": int(causal_pop1[j]),
                        "causal_pop2": int(causal_pop2[j]),
                        "z1_sumstat": pop1_z[j, 0],
                        "z1_cross": pop1_z[j, 1],
                        "z1_tissue": pop1_z[j, 2],
                        "z2_sumstat": pop2_z[j, 0],
                        "z2_cross": pop2_z[j, 1],
                        "z2_tissue": pop2_z[j, 2],
                        "zt_sumstat": method["zt"][j],
                        "z_meta": method["meta_z"][j],
                        "z_metatissue": method["meta_tissue_z"][j],
                        "pi_mean": pi_mean,
                        "run_gmm": int(method["run_gmm"]),
                        "run_gmm_tissue": int(method["run_gmm_tissue"]),
                    }
                )
            append_rows(result_path, out_rows, result_fields)

            for label, z in (
                ("pop1_sumstat", pop1_z[:, 0]),
                ("traceC", pop1_z[:, 1]),
                ("traceCB", pop1_z[:, 2]),
                ("meta", method["meta_z"]),
                ("meta_tissue", method["meta_tissue_z"]),
            ):
                pred = z2p(z) < P_VALUE_THRESHOLD
                noncausal = ~causal_pop1
                fpr_noncausal = (
                    float(np.mean(pred[noncausal])) if np.any(noncausal) else np.nan
                )
                power_shared = (
                    float(np.mean(pred[causal_pop1]))
                    if architecture == "shared" and np.any(causal_pop1)
                    else np.nan
                )
                power_pop1_specific = (
                    float(np.mean(pred[causal_pop1]))
                    if architecture == "pop1_specific" and np.any(causal_pop1)
                    else np.nan
                )
                alpha_null = float(np.mean(pred)) if architecture == "null" else np.nan
                alpha_pop2_specific = (
                    float(np.mean(pred)) if architecture == "pop2_specific" else np.nan
                )
                summary_rows.append(
                    {
                        "rep": rep,
                        "gene_id": gene_id,
                        "gene_name": gene_rows[0]["gene_name"],
                        "gene_type": gene_rows[0]["gene_type"],
                        "architecture": architecture,
                        "nsnp_gene": len(gene_rows),
                        "method": label,
                        "power": (
                            power_shared
                            if architecture == "shared"
                            else power_pop1_specific
                        ),
                        "alpha": (
                            alpha_null
                            if architecture == "null"
                            else alpha_pop2_specific
                        ),
                        "power_shared": power_shared,
                        "power_pop1_specific": power_pop1_specific,
                        "alpha_null": alpha_null,
                        "alpha_pop2_specific": alpha_pop2_specific,
                        "fpr_noncausal": fpr_noncausal,
                        "target_null_alpha": int(
                            architecture in {"null", "pop2_specific"}
                        ),
                        "run_gmm": int(method["run_gmm"]),
                        "run_gmm_tissue": int(method["run_gmm_tissue"]),
                    }
                )

            if gene_i % 100 == 0:
                print(f"rep {rep}: processed {gene_i}/{len(groups)} genes")

    write_rows(
        summary_path,
        summary_rows,
        [
            "rep",
            "gene_id",
            "gene_name",
            "gene_type",
            "architecture",
            "nsnp_gene",
            "method",
            "power",
            "alpha",
            "power_shared",
            "power_pop1_specific",
            "alpha_null",
            "alpha_pop2_specific",
            "fpr_noncausal",
            "target_null_alpha",
            "run_gmm",
            "run_gmm_tissue",
        ],
    )
    pop1_reader.close()
    if not one_prefix:
        pop2_reader.close()
    print(f"Saved SNP results to {result_path}")
    print(f"Saved gene summary to {summary_path}")
    print(f"Saved gene SNP counts to {gene_snp_count_path}")
    print_gene_snp_count_summary(gene_snp_count_rows)
    print(f"Finished in {time.time() - started:.2f} seconds")


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    setting_args = list(iter_setting_args(args))
    start_time = time.time()
    print("Simulation start at ", time.ctime())
    for i, setting in enumerate(setting_args, start=1):
        if args.dry_run:
            print(f"Dry run {i}/{len(setting_args)}: {setting.runname}")
            continue
        run_single_simulation(setting)
        print(f"Simulation {i}/{len(setting_args)} done, {time.ctime()}")
    print("Simulation end at ", time.ctime())
    print(
        f"Total time: {time.time() - start_time:.2f} s for {len(setting_args)} settings"
    )


if __name__ == "__main__":
    main()
